/**
 * Shared Booking Status Constants
 * Used across all models and controllers to ensure consistency
 */

export const BOOKING_STATUS = {
  PENDING_REVIEW: 'PENDING_REVIEW',
  REJECTED: 'REJECTED',
  CONFIRMED: 'CONFIRMED',
  PREPARATION_PENDING: 'PREPARATION_PENDING',
  REQUIREMENT_SUBMITTED: 'REQUIREMENT_SUBMITTED',
  READY_FOR_EVENT: 'READY_FOR_EVENT',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED'
};

export const PAYMENT_STATUS = {
  PAID: 'Paid',
  PARTIALLY_PAID: 'Partially Paid',
  UNPAID: 'Unpaid'
};

export const REQUIREMENT_STATUS = {
  PENDING: 'Pending',
  SUBMITTED: 'Submitted',
  APPROVED: 'Approved',
  REJECTED: 'Rejected'
};

export const EMPLOYEE_STATUS = {
  ACTIVE: 'Active',
  ON_LEAVE: 'On-leave',
  ASSIGNED: 'Assigned'
};

export const VEHICLE_STATUS = {
  AVAILABLE: 'available',
  ASSIGNED: 'assigned',
  MAINTENANCE: 'maintenance'
};

// Valid status transitions map
export const VALID_STATUS_TRANSITIONS = {
  [BOOKING_STATUS.PENDING_REVIEW]: [BOOKING_STATUS.REJECTED, BOOKING_STATUS.CONFIRMED],
  [BOOKING_STATUS.REJECTED]: [],
  [BOOKING_STATUS.CONFIRMED]: [BOOKING_STATUS.PREPARATION_PENDING],
  [BOOKING_STATUS.PREPARATION_PENDING]: [BOOKING_STATUS.REQUIREMENT_SUBMITTED],
  [BOOKING_STATUS.REQUIREMENT_SUBMITTED]: [BOOKING_STATUS.READY_FOR_EVENT],
  [BOOKING_STATUS.READY_FOR_EVENT]: [BOOKING_STATUS.IN_PROGRESS],
  [BOOKING_STATUS.IN_PROGRESS]: [BOOKING_STATUS.COMPLETED],
  [BOOKING_STATUS.COMPLETED]: []
};

export default {
  BOOKING_STATUS,
  PAYMENT_STATUS,
  REQUIREMENT_STATUS,
  EMPLOYEE_STATUS,
  VEHICLE_STATUS,
  VALID_STATUS_TRANSITIONS
};
